# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c8d136ad2af5a03a86bfeac7910458ae36b2e769d2d3eca82f8edf2d84fec9e12b716a56fd5adb2be566280f3a32326a4ecc490345a9fec7da62b55cba1299

test:
  secret_key_base: ed14242894427524e53111f77acec70d5632a599d3f5e953402994d6c2dc341b6d17157110022ba8f73abbf6e31810b3855db224b17caba72f0c87ce282aa769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
